services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
volumes:
  ollama: {}
